name: Tyrasoft Attendance CI

on:
  push: 
    tags: 
     - release-**
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          architecture: x64
      - run: flutter doctor
      - run: flutter --version
      - run: flutter pub get
      - run: pwd
      - run: chmod 777 ./*
      - run: echo $UPLOAD_KEY | base64 --decode
      - run: echo $UPLOAD_KEY | base64 --decode > android/app/upload-keystore.jks
      - run: echo $UPLOAD_KEY | base64 --decode > android/app/upload-keystore.txt
      - run: echo "storeFile=upload-keystore.jks" >> android/key.properties
      - run: echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> android/key.properties
      - run: echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> android/key.properties
      - run: echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> android/key.properties
      - name: Check key
        uses: actions/upload-artifact@v3
        with:
          name: check-key
          path: android
      - run: flutter build apk --release
